# Example Fly.io config
app = "mcp-cv-server-demo"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8787"

[[services]]
  internal_port = 8787
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
